name: 'Reminder'
outputs:

runs:
  using: 'docker'
  image: 'Dockerfile'

name: 'Reminder'

inputs:
  valid_week_type:
    description: 'odd, even, or all'
    default: all
outputs:
  should_skip:
    description: 'Whether the current week type should be skipped'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.valid_week_type}}
